image: registry.gitlab.com/offa/docker-images/docker-build:stable

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind


before_script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}



placeholder:
  script:
    - echo "*** Placeholder ***"
