image: registry.gitlab.com/offa/docker-images/docker-build:stable

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind


before_script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}



# ----------------------------------
# Stm32-eth Image Build
# ----------------------------------
build_stm32-eth_images:
  parallel:
    matrix:
      - COMPILER: gcc
        VERSION: [10, 9, 8, 7]
      - COMPILER: clang
        VERSION: [10, 9, 8, 7, 6, 5]
      - COMPILER: arm-none-eabi
        VERSION: [gcc]
  variables:
    DEPLOY_REGISTRY: ${CI_REGISTRY_IMAGE}/dist-stm32
  script:
    - git clone --depth=1 https://github.com/offa/stm32-eth stm32-eth
    - cd stm32-eth
    - ../script/build-image.sh ${COMPILER}-${VERSION} .


# ----------------------------------
# Danek Image Build
# ----------------------------------
build_danek_images:
  parallel:
    matrix:
      - COMPILER: gcc
        VERSION: [10, 9, 8, 7]
      - COMPILER: clang
        VERSION: [10, 9, 8, 7, 6, 5]
  variables:
    DEPLOY_REGISTRY: ${CI_REGISTRY_IMAGE}/dist-danek
  script:
    - git clone --depth=1 https://github.com/offa/danek danek
    - cd danek
    - ../script/build-image.sh ${COMPILER}-${VERSION} .


# ----------------------------------
# Keygen Image Build
# ----------------------------------
build_keygen_images:
  parallel:
    matrix:
      - COMPILER: gcc
        VERSION: [10, 9, 8, 7]
      - COMPILER: clang
        VERSION: [10, 9, 8, 7, 6, 5]
  variables:
    DEPLOY_REGISTRY: ${CI_REGISTRY_IMAGE}/dist-keygen
  script:
    - git clone --depth=1 https://github.com/offa/keygen keygen
    - cd keygen
    - ../script/build-image.sh ${COMPILER}-${VERSION} .


# ----------------------------------
# Matcher Image Build
# ----------------------------------
build_matcher_images:
  parallel:
    matrix:
      - COMPILER: gcc
        VERSION: [10, 9, 8, 7, 6]
      - COMPILER: clang
        VERSION: [10, 9, 8, 7, 6, 5]
  variables:
    DEPLOY_REGISTRY: ${CI_REGISTRY_IMAGE}/dist-matcher
  script:
    - git clone --depth=1 https://github.com/offa/matcher matcher
    - cd matcher
    - ../script/build-image.sh ${COMPILER}-${VERSION} .
