image: registry.gitlab.com/offa/docker-images/docker-build:stable

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind


before_script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}



# ----------------------------------
# Stm32-eth Image Build
# ----------------------------------
build_stm32-eth_images:
  parallel:
    matrix:
      - COMPILER: gcc
        VERSION: [11, 10, 9, 8, 7]
      - COMPILER: clang
        VERSION: [12, 11, 10, 9, 8, 7]
      - COMPILER: arm-none-eabi-gcc
        VERSION: [10]
  variables:
    DEPLOY_REGISTRY: ${CI_REGISTRY_IMAGE}/dist-stm32
  script:
    - git clone --depth=1 https://github.com/offa/stm32-eth stm32-eth
    - cd stm32-eth
    - ../script/build-image.sh ${COMPILER}-${VERSION} .


# ----------------------------------
# Keygen Image Build
# ----------------------------------
build_keygen_images:
  parallel:
    matrix:
      - COMPILER: gcc
        VERSION: [11, 10, 9, 8, 7]
      - COMPILER: clang
        VERSION: [12, 11, 10, 9, 8, 7]
  variables:
    DEPLOY_REGISTRY: ${CI_REGISTRY_IMAGE}/dist-keygen
  script:
    - git clone --depth=1 https://github.com/offa/keygen keygen
    - cd keygen
    - ../script/build-image.sh ${COMPILER}-${VERSION} .
