language: generic

dist: trusty
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - DEPLOY_REGISTRY: "registry.gitlab.com/offa/docker-images-ci"
    - IMAGE_NO_PUSH: true

matrix:
  include:
    # Stm32
    - env: PROJECT=stm32-eth BUILD=gcc-8
    - env: PROJECT=stm32-eth BUILD=gcc-7
    - env: PROJECT=stm32-eth BUILD=gcc-6
    - env: PROJECT=stm32-eth BUILD=clang-7
    - env: PROJECT=stm32-eth BUILD=clang-6
    - env: PROJECT=stm32-eth BUILD=clang-5
    - env: PROJECT=stm32-eth BUILD=arm-none-eabi-gcc
    # Danek
    - env: PROJECT=danek BUILD=gcc-8
    - env: PROJECT=danek BUILD=gcc-7
    - env: PROJECT=danek BUILD=clang-7
    - env: PROJECT=danek BUILD=clang-6
    - env: PROJECT=danek BUILD=clang-5
    # Keygen
    - env: PROJECT=keygen BUILD=gcc-8
    - env: PROJECT=keygen BUILD=gcc-7
    - env: PROJECT=keygen BUILD=gcc-6
    - env: PROJECT=keygen BUILD=clang-7
    - env: PROJECT=keygen BUILD=clang-6
    - env: PROJECT=keygen BUILD=clang-5
    # Matcher
    - env: PROJECT=matcher BUILD=gcc-8
    - env: PROJECT=matcher BUILD=gcc-7
    - env: PROJECT=matcher BUILD=gcc-6
    - env: PROJECT=matcher BUILD=clang-7
    - env: PROJECT=matcher BUILD=clang-6
    - env: PROJECT=matcher BUILD=clang-5


before_script:
  - git clone --depth=1 https://github.com/offa/${PROJECT} ${PROJECT}

script:
    - cd ${PROJECT}
    - ../script/build-image.sh ${BUILD} .

