name: ci

on: [push, pull_request]

env:
  DEPLOY_REGISTRY: "registry.gitlab.com/offa/docker-images-ci"
  IMAGE_NO_PUSH: true

jobs:
  build_images:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_config:
          ## stm32-eth
          - { project: "stm32-eth", compiler: "gcc", version: 11 }
          - { project: "stm32-eth", compiler: "gcc", version: 10 }
          - { project: "stm32-eth", compiler: "gcc", version: 9 }
          - { project: "stm32-eth", compiler: "gcc", version: 8 }
          - { project: "stm32-eth", compiler: "gcc", version: 7 }
          - { project: "stm32-eth", compiler: "clang", version: 12 }
          - { project: "stm32-eth", compiler: "clang", version: 11 }
          - { project: "stm32-eth", compiler: "clang", version: 10 }
          - { project: "stm32-eth", compiler: "clang", version: 9 }
          - { project: "stm32-eth", compiler: "clang", version: 8 }
          - { project: "stm32-eth", compiler: "clang", version: 7 }
          - { project: "stm32-eth", compiler: "arm-none-eabi-gcc", version: 10 }
          ## keygen
          - { project: "keygen", compiler: "gcc", version: 11 }
          - { project: "keygen", compiler: "gcc", version: 10 }
          - { project: "keygen", compiler: "gcc", version: 9 }
          - { project: "keygen", compiler: "gcc", version: 8 }
          - { project: "keygen", compiler: "gcc", version: 7 }
          - { project: "keygen", compiler: "clang", version: 12 }
          - { project: "keygen", compiler: "clang", version: 11 }
          - { project: "keygen", compiler: "clang", version: 10 }
          - { project: "keygen", compiler: "clang", version: 9 }
          - { project: "keygen", compiler: "clang", version: 8 }
          - { project: "keygen", compiler: "clang", version: 7 }
    name: "(${{ matrix.build_config.project }}) ${{ matrix.build_config.compiler }}-${{ matrix.build_config.version }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          git clone --depth=1 https://github.com/offa/${{ matrix.build_config.project }} ${{ matrix.build_config.project }}
          cd ${{ matrix.build_config.project }}
          ../script/build-image.sh ${{ matrix.build_config.compiler }}-${{ matrix.build_config.version }} .
