name: ci

on: [push, pull_request]

env:
  DEPLOY_REGISTRY: "registry.gitlab.com/offa/docker-images-ci"
  IMAGE_NO_PUSH: true

jobs:
  build_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_config:
          - { project: "placeholder", compiler: "noop", version: 0 }
    name: "(${{ matrix.build_config.project }}) ${{ matrix.build_config.compiler }}-${{ matrix.build_config.version }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: echo "*** Placeholder ***"
